# Site's name:
name: 'OpenHatch Events'

# Site's tagline:
tagline: "Open source meetups and training events"

# Site's URL with trailing slash:
url: 'http://events.openhatch.org/'

# Default timezone, run "rake -D time" for information on how to display known timezones:
timezone: 'UTC'

# Google map to display on /venues page:
venues_google_map_options:
  # Zoom magnification level:
  zoom: 12
  # Center of the map, in latitude and longitude:
  center: [45.518493, -122.660737]

# Array of tag names to exclude from tag cloud:
tagcloud_exclusions:
  - ostartupskey
  - tvg
